[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
mongodb = "2"
bson = "2"
futures = "0.3"
tracing = "0.1"
clickhouse = "0.11"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
fnv = "1.0"
